# This is a config for E2B sandbox template.
# You can use template ID (t34fs8vfat3d1pgyhlqo) or template name (vibe-prg1) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-prg1") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-prg1") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-prg1')

team_id = "a75085d8-9279-4bb8-803d-12f0254542ea"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-prg1"
template_id = "t34fs8vfat3d1pgyhlqo"
